
#define WORKED_OK 0
#define INVALID_HEX_DIGIT_IN_VALUE 1

#define INCOMING_HEX_VALUE_TOO_BIG_FOR_BUFFER 2
#define INCOMING_HEX_VALUE_IS_THE_WRONG_LENGTH 3


#define JSON_MESSAGE_COULD_NOT_BE_PARSED -1
#define JSON_MESSAGE_MISSING_COMMAND_NAME -2
#define JSON_MESSAGE_COMMAND_NAME_INVALID -3
#define JSON_MESSAGE_INVALID_DATA_TYPE -4
#define JSON_MESSAGE_INVALID_DATA_VALUE -5
#define INVALID_OR_MISSING_TARGET_IN_RECEIVED_COMMAND -6
#define COMMAND_FOR_DIFFERENT_TARGET -7
#define JSON_MESSAGE_PROCESS_NAME_MISSING -8
#define JSON_MESSAGE_PROCESS_NAME_INVALID -9
#define JSON_MESSAGE_COMMAND_MISSING_COMMAND -10
#define JSON_MESSAGE_COMMAND_COMMAND_NOT_FOUND -11
#define JSON_MESSAGE_COMMAND_ITEM_NOT_FOUND -12
#define JSON_MESSAGE_COMMAND_ITEM_NOT_INT -13
#define JSON_MESSAGE_COMMAND_ITEM_INVALID_TYPE -14
#define JSON_MESSAGE_COMMAND_ITEM_INVALID -15
#define JSON_MESSAGE_INVALID_COLOUR_NAME -16
#define JSON_MESSAGE_SERVO_VALUE_TOO_LOW -17
#define JSON_MESSAGE_SERVO_VALUE_TOO_HIGH -18
#define JSON_MESSAGE_NO_ROOM_TO_STORE_LISTENER -19
#define JSON_MESSAGE_NO_MATCHING_SENSOR_FOR_LISTENER -20
#define JSON_MESSAGE_NO_MATCHING_LISTENER_IN_SELECTED_SENSOR -21
#define JSON_MESSAGE_SENSOR_MISSING_TRIGGER -22
#define JSON_MESSAGE_SENSOR_ITEM_NOT_FOUND -23
#define JSON_MESSAGE_SERVO_NOT_AVAILABLE -24
#define JSON_MESSAGE_SENSOR_TRIGGER_NOT_FOUND -25
#define JSON_MESSAGE_DESTINATION_STRING_TOO_LONG -26
#define JSON_MESSAGE_LISTENER_COULD_NOT_BE_CREATED -27
#define JSON_MESSAGE_INVALID_CONSOLE_COMMAND -28
#define JSON_MESSAGE_INVALID_REGISTRATION_COMMAND -29
#define JSON_MESSAGE_MAX7219_NOT_ENABLED -30
#define JSON_MESSAGE_SETTINGS_NOT_FOUND -31
#define JSON_MESSAGE_MAX7219_INVALID_DEFAULT -32
#define JSON_MESSAGE_PRINTER_NOT_ENABLED -33
#define JSON_MESSAGE_SENSOR_NOT_FOUND_FOR_LISTENER_DELETE -34
#define JSON_MESSAGE_COULD_NOT_CREATE_STORE_FOLDER -35
#define JSON_MESSAGE_FILE_IN_PLACE_OF_STORE_FOLDER -36
#define JSON_MESSAGE_STORE_ID_MISSING_FROM_STORE_COMMAND -37
#define JSON_MESSAGE_STORE_FILENAME_INVALID -38
#define JSON_MESSAGE_STORE_FOLDERNAME_INVALID -39
#define JSON_MESSAGE_STORE_FOLDER_DOES_NOT_EXIST -40



